name: petal_viz_new
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.22.4
  - scipy=1.8.1
  - pip
  - pip:
    - PyQt5==5.15.9
    - pylsl>=1.16.0
    - pyqtgraph>=0.12.0